spring.application.name=encurtador
# Configuração de conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/encurtador
spring.datasource.username=postgres
spring.datasource.password=brenocmyk

# Atualiza a estrutura do banco automaticamente baseado nas nossas classes Java
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está rodando por trás dos panos
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true